version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: proxima_postgres
    environment:
      POSTGRES_DB: proxima_projects
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - proxima_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: proxima_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - proxima_network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: proxima_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - proxima_network

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: proxima_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - proxima_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: proxima_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - proxima_network

  # Kafka UI (opcional - para monitoramento)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: proxima_kafka_ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - proxima_network

  # Kibana (opcional - para visualização do Elasticsearch)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: proxima_kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - proxima_network

  # pgAdmin (opcional - para administração do PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: proxima_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@proxima.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - proxima_network

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:

networks:
  proxima_network:
    driver: bridge
