spring:
  application:
    name: proxima-project-manager
  
  datasource:
    url: jdbc:postgresql://localhost:5432/proxima_projects
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
    
    elasticsearch:
      uris: http://localhost:9200
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: proxima-project-manager
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

server:
  port: 8080

logging:
  level:
    com.proximaai: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: DEBUG

# Configurações de IA
proxima:
  ai:
    openai-api-key: ${OPENAI_API_KEY:}
    openai-model: gpt-3.5-turbo
    openai-base-url: https://api.openai.com/v1
    max-tokens: 1000
    temperature: 0.7
    
    # ML Configuration
    enable-ml-predictions: true
    enable-sentiment-analysis: true
    enable-delay-prediction: true
    enable-allocation-recommendation: true
    enable-project-summary: true
    
    # Performance Configuration
    prediction-cache-size: 1000
    analysis-cache-size: 500
    cache-expiration-minutes: 60
    
    # Thread Pool Configuration
    core-pool-size: 5
    max-pool-size: 20
    queue-capacity: 100

ai:
  openai:
    api-key: ${OPENAI_API_KEY:}
    model: gpt-3.5-turbo
    max-tokens: 1000
  
  huggingface:
    api-key: ${HUGGINGFACE_API_KEY:}
    model: microsoft/DialoGPT-medium

# Configurações de notificações
notifications:
  websocket:
    endpoint: /ws
    allowed-origins: "*"
  
  email:
    enabled: false
    smtp:
      host: smtp.gmail.com
      port: 587
      username: ${EMAIL_USERNAME:}
      password: ${EMAIL_PASSWORD:}

# Configurações de auditoria
audit:
  enabled: true
  retention-days: 365
